name: Actions Demo CI/CD workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v4        

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Create production release
        run: dotnet publish --configuration Release --no-build --output artifacts/release

      - name: Zip production release
        working-directory: artifacts/release
        run: zip --recurse-paths ../ActionsDemo.zip .

      - name: Store production release
        uses: actions/upload-artifact@v4
        with:
          name: ActionsDemo
          path: artifacts/ActionsDemo.zip
          if-no-files-found: error

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy App Service Tempalte
        run: az deployment group create --resource-group ActionsDemo --template-file ./main.bicep --parameters "appServiceName=jfactionsdemoprod"